# Generated by Django 3.1.5 on 2021-01-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('roll_no', models.CharField(max_length=3)),
                ('city', models.CharField(max_length=15)),
                ('school', models.CharField(max_length=30)),
            ],
        ),
    ]
